config:
  springProfilesActive: dev
  jpa:
    showSql: "true"
  graphql:
    graphiqlEnabled: "true"
  management:
    endpointsInclude: "*"
  logging:
    levelRoot: "INFO"
    levelApp: "DEBUG"
    levelSpringWeb: "INFO"

replicaCount: 1

resources:
  requests:
    memory: "128Mi"
    cpu: "50m"
  limits:
    memory: "256Mi"
    cpu: "150m"