config:
  springProfilesActive: dev
  jpa:
    showSql: "true"
  graphql:
    graphiqlEnabled: "true"
  management:
    endpointsInclude: "*"
  logging:
    levelRoot: "INFO"
    levelApp: "DEBUG"
    levelSpringWeb: "INFO"

replicaCount: 1

resources:
  requests:
    memory: "512Mi"
    cpu: "100m"
  limits:
    memory: "1Gi"
    cpu: "250m"