config:
  springProfilesActive: dev
  jpa:
    showSql: "true"
  graphql:
    graphiqlEnabled: "true"
  management:
    endpointsInclude: "*"
  logging:
    levelRoot: "INFO"
    levelApp: "DEBUG"
    levelSpringWeb: "INFO"
  swagger:
    enabled: "true"

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 250m
    memory: 512Mi