apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
data:
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  DB_URL: {{ .Values.config.database.url | quote }}
  DB_SCHEMA: {{ .Values.config.database.schema | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafka.bootstrapServers | quote }}
  KAFKA_CONSUMER_GROUP: {{ .Values.config.kafka.consumerGroup | quote }}
  JPA_SHOW_SQL: {{ .Values.config.jpa.showSql | quote }}
  GRAPHQL_GRAPHIQL_ENABLED: {{ .Values.config.graphql.graphiqlEnabled | quote }}
  MANAGEMENT_ENDPOINTS_INCLUDE: {{ .Values.config.management.endpointsInclude | quote }}
  SWAGGER_ENABLED: {{ .Values.config.swagger.enabled | quote }}
  SERVER_CONTEXT_PATH: {{ .Values.config.context.path | quote }}
  LOG_LEVEL_ROOT: {{ .Values.config.logging.levelRoot | quote }}
  LOG_LEVEL_APP: {{ .Values.config.logging.levelApp | quote }}
  LOG_LEVEL_SPRING_WEB: {{ .Values.config.logging.levelSpringWeb | quote }}